{{- if .Values.mySecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-pires.fullname" . }}-my-secret
  labels:
{{ include "kube-pires.labels" . | indent 4 }}
type: Opaque
data:
  password: {{ .Values.mySecret.mySecretLicenseKey | b64enc }}
{{- end }}